package com.shivam.backend.job;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "jobs")
public class Job {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) // DB auto-increment
    private Long id;

    @Column(nullable = false)
    private String title;

    @Column(nullable = false)
    private String company;

    private String location;

    @Column(length = 5000)
    private String description;

    @Column(precision = 10, scale = 2)
    private BigDecimal salaryFrom;

    @Column(precision = 10, scale = 2)
    private BigDecimal salaryTo;

    @Column(updatable = false)
    private LocalDateTime postedAt;

    private boolean isActive = true;

    // default constructor needed by JPA
    public Job() {}

    // getters & setters (generated by IDE)
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getTitle() { return title; }
    public void setTitle(String title) { this.title = title; }

    public String getCompany() { return company; }
    public void setCompany(String company) { this.company = company; }

    public String getLocation() { return location; }
    public void setLocation(String location) { this.location = location; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public BigDecimal getSalaryFrom() { return salaryFrom; }
    public void setSalaryFrom(BigDecimal salaryFrom) { this.salaryFrom = salaryFrom; }

    public BigDecimal getSalaryTo() { return salaryTo; }
    public void setSalaryTo(BigDecimal salaryTo) { this.salaryTo = salaryTo; }

    public LocalDateTime getPostedAt() { return postedAt; }
    public void setPostedAt(LocalDateTime postedAt) { this.postedAt = postedAt; }

    public boolean isActive() { return isActive; }
    public void setActive(boolean active) { isActive = active; }

    // set postedAt automatically before persist
    @PrePersist
    protected void onCreate() {
        this.postedAt = LocalDateTime.now();
    }
}

